export const actionTypes = {
    SET_PAGE_NUMBER: 'SET_PAGE_NUMBER',
    SET_ORIGINAL_TODOS: 'SET_ORIGINAL_TODOS',
    SET_FILTERED_TODOS: 'SET_FILTERED_TODOS',
    SET_SEARCH_TERM: 'SET_SEARCH_TERM',
    SET_SORT_BY: 'SET_SORT_BY',
    SET_STATUS_FILTER: 'SET_STATUS_FILTER',
    FETCH_SUCCESS:"FETCH_SUCCESS",
    FETCH_ERROR:"FETCH_ERROR"
};